'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class editar_evento

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lvEve As ListView
    Protected WithEvents lblusuario As Label
    Protected WithEvents TextFechaMod As TextBox
    Protected WithEvents TextHoraMod As TextBox
    Protected WithEvents TextTitulo As TextBox
    Protected WithEvents TextDescripcion As TextBox
    Protected WithEvents TextPlateaBaja As TextBox
    Protected WithEvents TextPlateaAlta As TextBox
    Protected WithEvents TextPlateaBajaDesc As TextBox
    Protected WithEvents TextPlateaAltaDesc As TextBox
    Protected WithEvents FileUpload1 As FileUpload
    Protected WithEvents checkbox As CheckBoxList
    Protected WithEvents ButtonModificar As Button


End Class
