'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ingresar_evento

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblusuario As Label
    Protected WithEvents TextFechaIng As TextBox
    Protected WithEvents TextHoraIng As TextBox
    Protected WithEvents TextTitulo As TextBox
    Protected WithEvents TextDescripcion As TextBox
    Protected WithEvents TextPlateaBaja As TextBox
    Protected WithEvents TextPlateaAlta As TextBox
    Protected WithEvents TextGaleria As TextBox
    Protected WithEvents FileUpload1 As FileUpload
    Protected WithEvents ButtonSubir As Button
End Class
